name: Testing Custom GitHub actions

on: 
  schedule:
    - cron: "*/5 * * * *"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: itzrahulyadav/Github-actions@main
